require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Ns::LlinksController do

  # This should return the minimal set of attributes required to create a valid
  # Ns::Llink. As you add validations to Ns::Llink, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Ns::LlinksController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all ns_llinks as @ns_llinks" do
      llink = Ns::Llink.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ns_llinks).should eq([llink])
    end
  end

  describe "GET show" do
    it "assigns the requested ns_llink as @ns_llink" do
      llink = Ns::Llink.create! valid_attributes
      get :show, {:id => llink.to_param}, valid_session
      assigns(:ns_llink).should eq(llink)
    end
  end

  describe "GET new" do
    it "assigns a new ns_llink as @ns_llink" do
      get :new, {}, valid_session
      assigns(:ns_llink).should be_a_new(Ns::Llink)
    end
  end

  describe "GET edit" do
    it "assigns the requested ns_llink as @ns_llink" do
      llink = Ns::Llink.create! valid_attributes
      get :edit, {:id => llink.to_param}, valid_session
      assigns(:ns_llink).should eq(llink)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ns::Llink" do
        expect {
          post :create, {:ns_llink => valid_attributes}, valid_session
        }.to change(Ns::Llink, :count).by(1)
      end

      it "assigns a newly created ns_llink as @ns_llink" do
        post :create, {:ns_llink => valid_attributes}, valid_session
        assigns(:ns_llink).should be_a(Ns::Llink)
        assigns(:ns_llink).should be_persisted
      end

      it "redirects to the created ns_llink" do
        post :create, {:ns_llink => valid_attributes}, valid_session
        response.should redirect_to(Ns::Llink.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ns_llink as @ns_llink" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ns::Llink.any_instance.stub(:save).and_return(false)
        post :create, {:ns_llink => {}}, valid_session
        assigns(:ns_llink).should be_a_new(Ns::Llink)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ns::Llink.any_instance.stub(:save).and_return(false)
        post :create, {:ns_llink => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ns_llink" do
        llink = Ns::Llink.create! valid_attributes
        # Assuming there are no other ns_llinks in the database, this
        # specifies that the Ns::Llink created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Ns::Llink.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => llink.to_param, :ns_llink => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested ns_llink as @ns_llink" do
        llink = Ns::Llink.create! valid_attributes
        put :update, {:id => llink.to_param, :ns_llink => valid_attributes}, valid_session
        assigns(:ns_llink).should eq(llink)
      end

      it "redirects to the ns_llink" do
        llink = Ns::Llink.create! valid_attributes
        put :update, {:id => llink.to_param, :ns_llink => valid_attributes}, valid_session
        response.should redirect_to(llink)
      end
    end

    describe "with invalid params" do
      it "assigns the ns_llink as @ns_llink" do
        llink = Ns::Llink.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ns::Llink.any_instance.stub(:save).and_return(false)
        put :update, {:id => llink.to_param, :ns_llink => {}}, valid_session
        assigns(:ns_llink).should eq(llink)
      end

      it "re-renders the 'edit' template" do
        llink = Ns::Llink.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ns::Llink.any_instance.stub(:save).and_return(false)
        put :update, {:id => llink.to_param, :ns_llink => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ns_llink" do
      llink = Ns::Llink.create! valid_attributes
      expect {
        delete :destroy, {:id => llink.to_param}, valid_session
      }.to change(Ns::Llink, :count).by(-1)
    end

    it "redirects to the ns_llinks list" do
      llink = Ns::Llink.create! valid_attributes
      delete :destroy, {:id => llink.to_param}, valid_session
      response.should redirect_to(ns_llinks_url)
    end
  end

end
